### ISSUE TITLE
Alternating Queries Solution

### ISSUE THREAD

**Issue by Gaurav5ingh** [notabhishek/Competitive-Programming#2]
Great solutions!! Just one hitch in the solution of Alternating Queries. In merge function, for prefix/suffix part of the vectors (pp, pn, np, nn) whole sum of left/right child is used, which I think doesn't take alternating signs into account. Instead of keeping just a normal sum, we can have two alternating sums starting with positive & negative signs. While merging we will have to check the length of subarray covered in the left child (len is already maintained in the code) in order to add the correct sum (+/-) from the right child to get the (+/-) sums for current node. Something like this:- 
```
u.posSum = l.posSum + (l.len & 1? r.posSum: r.negSum);
u.negSum = l.negSum + (l.len & 1? r.negSum: r.posSum);
```

**Comment by notabhishek** [comment]
That is actually not needed since we are actually maintaining alternating sums, 
pp means alternating sum starting with a positive sign and ending on a negative sign, 
similarly, pn means starting at a positive sign and ending on a negative sign.

consider, 
```
cur.pp[1] = max(l.pp[1], l.sum + (l.len%2 ? r.np[1] : r.pp[1]));
````
if l.len is odd, L ends in a p ( p-p +-+-...+ ) so we decide the starting and ending sign of R ( R.np  ) 
else  L ends in a n (p-n +-+-+- ) so we start R using a positive sign R.pp 

and that is what I did here  (l.len%2 ? r.np[1] : r.pp[1]));

and similarly for other 3 cases 
```
cur.pn[1] = max(l.pn[1], l.sum + (l.len%2 ? r.nn[1] : r.pn[1]));
cur.np[1] = max(l.np[1], -l.sum + (l.len%2 ? r.pp[1] : r.np[1]));
cur.nn[1] = max(l.nn[1], -l.sum + (l.len%2 ? r.pn[1] : r.nn[1]));
```

**Comment by Gaurav5ingh** [comment]
I already got your idea and completely agree with it. But my only concern here is how exactly 'l.sum' is accommodating alternating signs, instead, I think it behaves like a normal sum. The reason being you have kept the array value in 'sum' for the leaves of segTree, and while merging, you have simply added the left and right children's 'sum' to the current node's 'sum'.

**Comment by notabhishek** [comment]
Oh! I think it is a mistake, it should be something like 
```
cur.sum = l.sum + ( (l.len & 1) ? : -r.sum : r.sum); 
```
